<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-26 at 12:56:09.
 */
class jigoshop_shipping_methodTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jigoshop_shipping_method
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jigoshop_shipping_method;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jigoshop_shipping_method::is_available
     * @todo   Implement testIs_available().
     */
    public function testIs_available() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_error_message
     * @todo   Implement testGet_error_message().
     */
    public function testGet_error_message() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::set_error_message
     * @todo   Implement testSet_error_message().
     */
    public function testSet_error_message() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_enabled
     * @todo   Implement testGet_enabled().
     */
    public function testGet_enabled() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::set_tax
     * @todo   Implement testSet_tax().
     */
    public function testSet_tax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_fee
     * @todo   Implement testGet_fee().
     */
    public function testGet_fee() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::is_chosen
     * @todo   Implement testIs_chosen().
     */
    public function testIs_chosen() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::choose
     * @todo   Implement testChoose().
     */
    public function testChoose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::set_selected_service_index
     * @todo   Implement testSet_selected_service_index().
     */
    public function testSet_selected_service_index() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_cheapest_service
     * @todo   Implement testGet_cheapest_service().
     */
    public function testGet_cheapest_service() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_cheapest_price
     * @todo   Implement testGet_cheapest_price().
     */
    public function testGet_cheapest_price() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_selected_service
     * @todo   Implement testGet_selected_service().
     */
    public function testGet_selected_service() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_selected_price
     * @todo   Implement testGet_selected_price().
     */
    public function testGet_selected_price() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_selected_tax
     * @todo   Implement testGet_selected_tax().
     */
    public function testGet_selected_tax() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::get_rates_amount
     * @todo   Implement testGet_rates_amount().
     */
    public function testGet_rates_amount() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::has_error
     * @todo   Implement testHas_error().
     */
    public function testHas_error() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::reset_method
     * @todo   Implement testReset_method().
     */
    public function testReset_method() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::admin_options
     * @todo   Implement testAdmin_options().
     */
    public function testAdmin_options() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_shipping_method::process_admin_options
     * @todo   Implement testProcess_admin_options().
     */
    public function testProcess_admin_options() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
