<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-26 at 12:56:11.
 */
class Jigoshop_BaseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Jigoshop_Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Jigoshop_Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Jigoshop_Base::get_options
     * @todo   Implement testGet_options().
     */
    public function testGet_options()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
