<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-26 at 12:56:09.
 */
class jigoshop_payment_gatewayTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var jigoshop_payment_gateway
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new jigoshop_payment_gateway;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers jigoshop_payment_gateway::is_available
     * @todo   Implement testIs_available().
     */
    public function testIs_available()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::set_current
     * @todo   Implement testSet_current().
     */
    public function testSet_current()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::icon
     * @todo   Implement testIcon().
     */
    public function testIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::admin_options
     * @todo   Implement testAdmin_options().
     */
    public function testAdmin_options()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::process_payment
     * @todo   Implement testProcess_payment().
     */
    public function testProcess_payment()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::validate_fields
     * @todo   Implement testValidate_fields().
     */
    public function testValidate_fields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_payment_gateway::process_gateway
     * @todo   Implement testProcess_gateway().
     */
    public function testProcess_gateway()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
