<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-11-26 at 12:56:05.
 */
class jigoshop_validationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jigoshop_validation
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jigoshop_validation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jigoshop_validation::is_integer
     * @todo   Implement testIs_integer().
     */
    public function testIs_integer() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_natural
     * @todo   Implement testIs_natural().
     */
    public function testIs_natural() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_decimal
     * @todo   Implement testIs_decimal().
     */
    public function testIs_decimal() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_email
     * @todo   Implement testIs_email().
     */
    public function testIs_email() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_phone
     * @todo   Implement testIs_phone().
     */
    public function testIs_phone() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_postcode
     * @todo   Implement testIs_postcode().
     */
    public function testIs_postcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::is_GB_postcode
     * @todo   Implement testIs_GB_postcode().
     */
    public function testIs_GB_postcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jigoshop_validation::format_postcode
     * @todo   Implement testFormat_postcode().
     */
    public function testFormat_postcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
